#!/usr/bin/php
<?php

require __DIR__ . '/../init.php';

use gaswelder\htmlparser\dom\ElementNode;
use \gaswelder\htmlparser\Parser;

// Script path.
array_shift($argv);

define('USAGE', "usage: htmlcut [-i] <selector> <filepath> ...");
$invert = false;
$selector = '';

while (count($argv) > 0 && $argv[0][0] == '-') {
    if ($argv[0] == '-i') {
        $invert = true;
        array_shift($argv);
    } else if ($argv[0] == "-h") {
        printf(USAGE . "\n");
        printf("\t-k\tinvert selection: keep matches, remove rest\n");
        exit(0);
    } else {
        fprintf(STDERR, "unknown flag: $argv[0]\n");
        exit(1);
    }
}

$selector = array_shift($argv);
if (!$selector) {
    fprintf(STDERR, USAGE . "\n");
    exit(1);
}

function forall(ElementNode $e, callable $f)
{
    $f($e);
    foreach ($e->children as $c) {
        forall($c, $f);
    }
}

if ($invert) {
    foreach ($argv as $arg) {
        try {
            $doc = Parser::parse(file_get_contents($arg));
        } catch (Exception $e) {
            echo "$arg: " . $e->getMessage();
            continue;
        }
        $n = $doc->querySelector($selector);
        if ($n == NULL) {
            continue;
        }
        echo $arg, "\n";
        file_put_contents($arg, $n->innerHTML());
    }
} else {
    foreach ($argv as $arg) {
        try {
            $doc = Parser::parse(file_get_contents($arg));
        } catch (Exception $e) {
            echo "$arg: " . $e->getMessage();
            continue;
        }
        $n = 0;


        $sels = explode(',', $selector);
        foreach ($sels as $sel) {
            if ($sel[0] == '@') {
                $k = substr($sel, 1);
                foreach ($doc->children as $c) {
                    forall($c, function ($e) use ($k, &$n) {
                        if ($e->getAttribute($k) !== null) {
                            $e->removeAttribute($k);
                            $n++;
                        }
                    });
                }
            } else {
                foreach ($doc->querySelectorAll($sel) as $e) {
                    $e->remove();
                    $n++;
                }
            }
        }

        if ($n > 0) {
            echo $arg, "\n";
            $s = $doc->format();
            file_put_contents($arg, $s);
        }
    }
}
