#!/usr/bin/php
<?php

require __DIR__ . '/../init.php';

use \gaswelder\htmlparser\Parser;

// Script path.
array_shift($argv);

define('USAGE', "usage: htmlcut [-i] <selector> <filepath> ...");
$invert = false;
$selector = '';

while (count($argv) > 0 && $argv[0][0] == '-') {
    if ($argv[0] == '-i') {
        $invert = true;
        array_shift($argv);
    } else if ($argv[0] == "-h") {
        printf(USAGE . "\n");
        printf("\t-k\tinvert selection: keep matches, remove rest\n");
        exit(0);
    } else {
        fprintf(STDERR, "unknown flag: $argv[0]\n");
        exit(1);
    }
}

$selector = array_shift($argv);
if (!$selector) {
    fprintf(STDERR, USAGE . "\n");
    exit(1);
}

foreach ($argv as $arg) {
    try {
        $doc = Parser::parse(file_get_contents($arg));
    } catch (Exception $e) {
        echo "$arg: " . $e->getMessage();
        continue;
    }
    if ($invert) {
        $n = $doc->querySelector($selector);
        if ($n == NULL) {
            continue;
        }
        echo $arg, "\n";
        file_put_contents($arg, $n->innerHTML());
        continue;
    }

    $n = 0;
    foreach ($doc->querySelectorAll($selector) as $e) {
        $e->remove();
        $n++;
    }
    if ($n > 0) {
        echo $arg, "\n";
        $s = $doc->format();
        file_put_contents($arg, $s);
    }
}
