#!/usr/bin/php
<?php

require __DIR__ . '/../init.php';

use \gaswelder\htmlparser\Parser;

$selector = '';

array_shift($argv);
$selector = array_shift($argv);
if (!$selector) {
    fprintf(STDERR, "usage: htmlcut <selector> <filepath> ...\n");
    exit(1);
}

foreach ($argv as $arg) {
    $doc = Parser::parse(file_get_contents($arg));
    $n = 0;
    foreach ($doc->querySelectorAll($selector) as $e) {
        $e->remove();
        $n++;
    }
    if ($n > 0) {
        echo $arg, "\n";
        $s = $doc->format();
        file_put_contents($arg, $s);
    }
}
